[package]
name = "canvas-wasm"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "0.3.77"
wasm-bindgen = "0.2.100"
web-sys = { version = "0.3.77", features = [
  "CanvasRenderingContext2d",
  "HtmlCanvasElement",
  "Window",
] }
